COL_ID = 1
COL_TITLE = 2
COL_LOCATION = 3
COL_STATUS = 4
COL_LAST_UPDATED = 5
COL_BUDGET = 6
COL_LOG = 7

# RUNS.md column indices
RUNS_COL_ID = 1
RUNS_COL_TITLE = 2
RUNS_COL_STATUS = 3
RUNS_COL_LAST_UPDATED = 4
RUNS_COL_LOG = 5

# WORK-CHILDREN.md column indices
CH_ID = 1
CH_TITLE = 2
CH_STATUS = 3
CH_LAST_UPDATED = 4

POLL_INTERVAL_S = 5
POLL_CYCLES_PER_MIN = 60 // POLL_INTERVAL_S  # = 12
DEFAULT_TIMEOUT_MIN = 4
CH_BUDGET = 5
CH_LOG = 6
